### ISSUE TITLE
Support OS X projects

### ISSUE THREAD

**Issue by jberkel** [bitrise-io/steps-xcode-test#23]
Maybe this is out of scope, but OS X projects don't build properly since "-device" is always passed to xcodebuild, which does not make sense for an OS X project.

**Comment by viktorbenei** [comment]
We're working on OS X specific steps, and OS X app support in general, you can follow the progress at: https://github.com/bitrise-io/bitrise-contrib/issues/1

That said, running OS X tests does not require the workaround we use because of the iOS Simulator, and can be done with a simple Script step ( https://github.com/bitrise-io/bitrise-gui-osx/blob/master/bitrise.yml#L40 ).

**Comment by viktorbenei** [comment]
Closed the issue, because we don't plan to add OS X support to this Step. Mainly because this step has way too many inputs which are not required for OS X projects, and would potentially confuse users.

**Comment by jberkel** [comment]
Sure, I already use a plain script step to build the project w/o problems. Just thought I'd mentioned it, "Xcode build step" sounds like it is universal, maybe it should be renamed to "iOS Xcode build step" in order to avoid confusion.

**Comment by viktorbenei** [comment]
That's a good idea, and we'll definitely provide an OS X specific version of this step in the near future, as a separate Step.
