### ISSUE TITLE
Step does not save log if not using xcpretty

### ISSUE THREAD

**Issue by russbishop** [bitrise-io/steps-xcode-test#29]
The step apparently doesn't save a log file if you don't use xcpretty and because `BITRISE_XCODE_TEST_FULL_RESULTS_TEXT` was removed you can't post-process the log output anymore.

Secondly, the step still claims this is a valid environment variable so the text should be updated.

Lastly, it would be really nice if you could get both the raw log and the xcpretty output. Using `tee` or the go pipe stuff it should be fairly easy to do that.

Background: I'm working on a step to automatically comment on pull requests when a build fails and include the failing test lines from the log. I already have everything working locally, I just can't get the actual log output for processing.

**Comment by viktorbenei** [comment]
> Secondly, the step still claims this is a valid environment variable so the text should be updated.

This should be an issue on bitrise.io, maybe it copied the text or the outputs of the step when you upgraded the version, as the latest version does not include this Env anymore ( https://github.com/bitrise-io/steps-xcode-test/blob/master/step.yml ).

> Lastly, it would be really nice if you could get both the raw log and the xcpretty output

That sounds reasonable, and with the latest version of the step this should be easy to do - because it already stores both outputs internally.

Just one note: the step now has separate Build and Test phases, to make the logs shorter/easier to check as a user. Do you need the full log (including both the build & test) or you're OK with getting only the test log? In case of a build error it would be of course the build log, but if the build is successful the step right now does not store the build output, only stores/prints the test output.

**Comment by russbishop** [comment]
Only the test log is fine with me; if the build was successful then I don't need that log. I'm actually checking for `BITRISE_XCODE_TEST_RESULT` == `failure` before I do anything.

**Comment by viktorbenei** [comment]
Added to our list - we'll start with this next week.

**Comment by viktorbenei** [comment]
`v1.10.0` is now out and includes this: https://github.com/bitrise-io/steps-xcode-test/releases/tag/1.10.0

Thanks for the request! 😉
