### ISSUE TITLE
xcode test failed, error: exit status 65

### ISSUE THREAD

**Issue by jonchui** [bitrise-io/steps-xcode-test#47]
our tests are just Xcode's examples, which have nothing and pass (at least that's what the logs show below). 

Could it be related to https://github.com/bitrise-io/bitrise.io/issues/5 ?

=================== LOG BELOW ==============

Test Suite ReadScriptureTests.xctest started
ReadScriptureTests
    ✓ testExample (0.000 seconds)
    ◷ testPerformanceExample measured (0.000 seconds)
    ✓ testPerformanceExample (0.411 seconds)
	 Executed 2 tests, with 0 failures (0 unexpected) in 0.412 (0.414) seconds
xcode test exit code: 65
xcode test failed, error: exit status 65
exit status 1
ERRO[19:21:15] Step (Xcode: Unit Test) failed, error: (exit status 1) 
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | Xcode: Unit Test (exit code: 1)                              | 169 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-xcode-test/issues         |
| Source: https://github.com/bitrise-io/steps-xcode-test                       |
+----+--------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
Hi,

I don't think it would be related to that issue.

Can you provide a sample app we could reproduce this issue with?
Also, you can try to change the Output Tool option of this step from the default `xcpretty` to `xcodebuild`, it can be that `xcpretty` omits the error message which causes the test to fail, or that `xcpretty` is the reason why it fails.

**Comment by jonchui** [comment]
I've changed to xcodebuild, and i still get the same error. 

here's the full log:
https://dl.dropboxusercontent.com/u/2125626/10a3c832337789d4.log

The sample app we have is on a private github repo - if the log isn't sufficient, lmk and i'll see if i can get a copy of the app for you

**Comment by viktorbenei** [comment]
@jonchui I was wrong, it's definitely related to https://github.com/bitrise-io/bitrise.io/issues/5

You can also find a formatted collection of possible solutions here: https://github.com/bitrise-io/bitrise.io/blob/master/known-xcode-issues.md#xcode-unit-test-fails-without-any-error-with-exit-code-65

Unfortunately this is an Xcode (`xcodebuild`) bug/issue and can be caused by quite a lot of things. You should check these two links and try to solutions reported by other users.

If you can find out what's the issue in your case please let us know here!
