### ISSUE TITLE
isAutomaticRetryOnReason hardcoded to true

### ISSUE THREAD

**Issue by gringoireDM** [bitrise-io/steps-xcode-test#79]
Currently there is no option to disable the auto retry on this step (isAutomaticRetryOnReason), doubling the build time for failing builds. A toggle would be appreciated.

**Comment by godrei** [comment]
Hi @gringoireDM ,

We designed the step, to automatically rerun the test, it it failed because of an issue, which is not related to the test run. We collect these issues and we call it to: `Automatic retry reasons`, these issues are related to the ios simulator (may its not booted yet, or not setup correctly yet). You can not trun off this retry, since your test would fail, even if its not because of your test cases...

Using `(Experimental) Rerun test, when it fails?` step input you can control if the step should rerun the test if it failed with any issue or not.

Do you think that an option to disabling `Automatic retry reasons` would be reasonable?

**Comment by gringoireDM** [comment]
Hi, @godrei I think we already spoke on the Bitrise customer portal. Anyway this is causing the build on Xcode 9 to run twice regardless of success or failure conditions doubling the time for each build.

**Comment by godrei** [comment]
The step retries the test run if:
- the xcodebuild test log contains one of the [Automatic retry reasons](https://github.com/bitrise-io/steps-xcode-test/blob/master/main.go#L46)
- or the test run failed and `(Experimental) Rerun test, when it fails?` step input is set to `true`

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
